kind: pipeline
name: default

steps:
- name: info
  image: alpine:3.9
  commands:
  - hostname
  - uname -a 
  - pwd
  - uptime
  - free -mh
  - cat /proc/cpuinfo
- name: test
  image: node:9.3.0-slim
  commands:
  - hostname
  - npm install
  - npm test
- name: docker  
  image: plugins/docker
  settings:
    dry_run: true
    repo: kkapelon/nest-sample
    tags: latest
- name: docker-multi  
  image: plugins/docker
  settings:
    dry_run: true
    repo: kkapelon/nest-sample
    tags: multi
    dockerfile: Dockerfile.multi
- name: manualdocker
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker ps -a

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
