kind: pipeline
name: default

steps:
- name: info
  image: alpine:3.9
  commands:
  - uname -a 
  - pwd
  - uptime
  - free -mh
  - cat /proc/cpuinfo
- name: test
  image: node:9.3.0-slim
  commands:
  - npm install
  - npm test
- name: docker  
  image: plugins/docker
  settings:
    dry_run: true
    repo: kkapelon/nest-sample
    tags: latest
- name: docker-multi  
  image: plugins/docker
  settings:
    dry_run: true
    repo: kkapelon/nest-sample
    tags: multi
    dockerfile: Dockerfile.multi
